channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=22.2.1
- pip:
  - numpy==1.24.4
  - dagshub==0.5.10
  - imblearn==0.0
  - matplotlib==3.10.3
  - mlflow==2.22.0
  - mlflow_skinny==2.22.0
  - mpld3==0.5.10
  - pandas==2.2.3
  - scikit_learn==1.6.1
  - scipy==1.15.3
  - seaborn==0.13.2
  - shap==0.47.2
  - xgboost==3.0.2  

name: mlflow-env
