name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.12.9
  - pip<=25.1
  - pip:
      - mlflow==2.19.0
      - cloudpickle==3.1.1
      - numpy==2.2.5
      - pandas==2.2.3
      - psutil==5.9.0
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - xgboost==2.0.3
      - imbalanced-learn==0.12.2
      - shap==0.44.1
      - matplotlib==3.9.0
      - mpld3==0.5.10
      - seaborn==0.13.2
